/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thewithel_JniExample */

#ifndef _Included_com_thewithel_JniExample
#define _Included_com_thewithel_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thewithel_JniExample
 * Method:    callJavaMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thewithel_JniExample_callJavaMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_thewithel_JniExample
 * Method:    createAndReturnBean
 * Signature: ()Lcom/thewithel/Bean;
 */
JNIEXPORT jobject JNICALL Java_com_thewithel_JniExample_createAndReturnBean
  (JNIEnv *, jobject);

/*
 * Class:     com_thewithel_JniExample
 * Method:    modifyBean
 * Signature: (Lcom/thewithel/Bean;)V
 */
JNIEXPORT void JNICALL Java_com_thewithel_JniExample_modifyBean
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_thewithel_JniExample
 * Method:    crashTheJvm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thewithel_JniExample_crashTheJvm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
